#!/bin/bash
SOURCE_DIR="/source/oscar"
NEXT_DIR="/next/oscar"
ACTIVE_DIR="/active/oscar"
ARCHIVE_DIR="/archive/oscar"
SCRATCH_SLOW_DIR="/scratch/slow/oscar"
SCRATCH_FAST_DIR="/scratch/fast/oscar"
OSCAR_LOG_DIR="/var/log/oscar-web"
OSCAR_UPDATE_LOG_DIR="${OSCAR_LOG_DIR}/update"
source "/etc/oscar-options.sh"